### ISSUE TITLE
Package build enhancements

### ISSUE THREAD

**Issue by MaceM8** [lundegaard/lundium#13]
Amend current build config in order to have optimized bundle on npm. 
Consider optimizin usage of dependencies like `ramda` or `ramda-extension`.

**Comment by tommmyy** [comment]
@MaceM8 can we close it?

**Comment by MaceM8** [comment]
This issue will be resolved with #25 . 
It was partly solved by moving build config to appropriate package, but its not done. 

We can close it, but this one and #25 are focused on slightly different thing, so I'd leave it open.
